{% set name = "swiglpk" %}
{% set version = "4.65.0" %}
{% set sha256 = "389e4179bf8eeeeb1d2e215298e133c961855998ed63da9d7d2e1fa207bb9fec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/biosustain/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win]

requirements:
  build:
    - python
    - pip
    - swig
    - glpk

  run:
    - python
    - swig
    - glpk

test:
  imports:
    - swiglpk

about:
  home: https://github.com/biosustain/swiglpk
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Simple swig bindings for the GNU Linear Programming Kit'
  description: |
    swiglpk is not a high-level wrapper for GLPK (take a look at optlang 
    if you are interested in a python-based mathematical programming language). 
    It just provides plain vanilla swig bindings to the underlying C library.
  dev_url: https://github.com/biosustain/swiglpk

extra:
  recipe-maintainers:
    - druvus
