{% set version = "5.0.10" %}
{% set sha256 = "4df7cc42ed2ea83f389577e77272c607503bb92b3bab769c86fc78bfc32cbab7" %}

package:
  name: swiglpk
  version: {{ version }}

source:
  url: https://github.com/biosustain/swiglpk/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [unix]
    - swig
  host:
    - python
    - pip
    - glpk >=5.0.0
  run:
    - python
    - glpk >=5.0.0

test:
  imports:
    - swiglpk

about:
  home: https://github.com/biosustain/swiglpk
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Simple swig bindings for the GNU Linear Programming Kit
  description: |
    swiglpk is not a high-level wrapper for GLPK (take a look at optlang
    if you are interested in a python-based mathematical programming language).
    It just provides plain vanilla swig bindings to the underlying C library.
  dev_url: https://github.com/biosustain/swiglpk

extra:
  recipe-maintainers:
    - druvus
    - cdiener
