appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: KNH+Y+KRdyA31MLukTDqPK42zkyyjTKTPaNkr/buEewhuSq0uoNAQorTXpLQrJIuiGWE35c4hCegDF4hUs6F+MDBZukJRfAtWT4INFQSw24+nsbf0GsckO02FHlMJT8eW0pEkWau92N7o5SqyQnjr3zY3P4aw2/nDq/43/w3hvKxK+EEWMe0S5LtIZc/0Z89DbT8/364C7VxIzIPYfpZ5iRQWXRwqqAH96J9HdvJMgH9ysUDx8ckuIJnl8jyR4gyXb8VTJADEYdj1elGdU/WRnvJTIDzM8DNHEs8/XkVlfRjC7MQzHAEZrmLPN4xXal7hd0cQjd/uw3Ha6ufDU+Ga4ZbjNkSzIGDXM2ILMTNthlWbw9suUsiebUgUiUdLg7uv2qlj1812Widc2HrSFpDCU70cBVGWDfQ9XNb0tGRM16Nc+4bdh/KZhTW3swkt3ahaeads5pFIXWa1xcqNsM4QUI17WAT3b+M/tyUNN1ytJj3MilDodids7Z/kydedolnhSAkhA+TKiI4F9jCdjjIlRZyUPSm856gFpxw/5Et+xrly1kUBBp40p35uAMN1dclQ7gEwwNmefbmvNpdw2YE3V+iopnEpdmPPLNOCRDIcX+rwhw9u9+p03hzt+gw0WX8OjprrJ+Nv224ihBb3qrSM1r4WIyZjvLkb5c8+B6Ymkc=}
conda_forge_output_validation: true
bot:
  automerge: true
